###
POST http://localhost:8080/users HTTP/1.1
content-type: application/json

{
    "name": "sample3",
    "email": "sample3@test"
}

###
GET http://localhost:8080/users HTTP/1.1

###
GET http://localhost:8080/users/1 HTTP/1.1

###
PUT http://localhost:8080/users/1 HTTP/1.1
content-type: application/json

{
    "name": "sample2a",
    "email": "sample2a@test"
}

###
DELETE http://localhost:8080/users/2 HTTP/1.1